In [1]:
# Dependencies and Setup
import pandas as pd
import json
import numpy as np

# SQL Alchemy Dependencies
import sqlalchemy
from sqlalchemy import create_engine

In [2]:
# Read movie_metadata.csv into movie_df
movie_df = pd.read_csv("Resources/movie_metadata.csv")
movie_df.rename(columns={'movie_title':'title'}, inplace=True)

In [3]:
# Read all_script.csv into script_df
script_df = pd.read_csv("Resources/updated_all_script.csv")
script_df

,title,Swear_Count,Fuck_Count,Shit_Count,Bitch_Count,Cunt_Count,Profanity
0,10 Things I Hate About You,15,3,6,6,0,TRUE
1,12,2,2,0,0,0,TRUE
2,12 and Holding,21,10,10,1,0,TRUE
3,12 Monkeys,17,11,4,2,0,TRUE
4,12 Years a Slave,1,0,0,1,0,TRUE
...,...,...,...,...,...,...,...
1206,You've Got Mail,9,4,4,1,0,TRUE
1207,Youth in Revolt,6,2,4,0,0,TRUE
1208,Zero Dark Thirty,44,41,2,1,0,TRUE
1209,Zerophilia,18,14,4,0,0,TRUE
1210,Zootopia,0,0,0,0,0,[]

In [4]:
movie_df.dtypes

color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
title                         object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object

In [5]:
# Select
cleaned_movie_df = movie_df[["title","director_name","genres","duration","title_year","budget","content_rating","imdb_score","gross","actor_1_name","actor_2_name","actor_3_name","facenumber_in_poster","cast_total_facebook_likes","imdb_score","plot_keywords","country"]]
cleaned_movie_df

,title,director_name,genres,duration,title_year,budget,content_rating,imdb_score,gross,actor_1_name,actor_2_name,actor_3_name,facenumber_in_poster,cast_total_facebook_likes,imdb_score,plot_keywords,country
0,Avatar,James Cameron,Action|Adventure|Fantasy|Sci-Fi,178.0,2009.0,237000000.0,PG-13,7.9,760505847.0,CCH Pounder,Joel David Moore,Wes Studi,0.0,4834,7.9,avatar|future|marine|native|paraplegic,USA
1,Pirates of the Caribbean: At World's End,Gore Verbinski,Action|Adventure|Fantasy,169.0,2007.0,300000000.0,PG-13,7.1,309404152.0,Johnny Depp,Orlando Bloom,Jack Davenport,0.0,48350,7.1,goddess|marriage ceremony|marriage proposal|pi...,USA
2,Spectre,Sam Mendes,Action|Adventure|Thriller,148.0,2015.0,245000000.0,PG-13,6.8,200074175.0,Christoph Waltz,Rory Kinnear,Stephanie Sigman,1.0,11700,6.8,bomb|espionage|sequel|spy|terrorist,UK
3,The Dark Knight Rises,Christopher Nolan,Action|Thriller,164.0,2012.0,250000000.0,PG-13,8.5,448130642.0,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,0.0,106759,8.5,deception|imprisonment|lawlessness|police offi...,USA
4,Star Wars: Episode VII - The Force Awakens ...,Doug Walker,Documentary,NaN,NaN,NaN,NaN,7.1,NaN,Doug Walker,Rob Walker,NaN,0.0,143,7.1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Signed Sealed Delivered,Scott Smith,Comedy|Drama,87.0,2013.0,NaN,NaN,7.7,NaN,Eric Mabius,Daphne Zuniga,Crystal Lowe,2.0,2283,7.7,fraud|postal worker|prison|theft|trial,Canada
5039,The Following,NaN,Crime|Drama|Mystery|Thriller,43.0,NaN,NaN,TV-14,7.5,NaN,Natalie Zea,Valorie Curry,Sam Underwood,1.0,1753,7.5,cult|fbi|hideout|prison escape|serial killer,USA
5040,A Plague So Pleasant,Benjamin Roberds,Drama|Horror|Thriller,76.0,2013.0,1400.0,NaN,6.3,NaN,Eva Boehnke,Maxwell Moody,David Chandler,0.0,0,6.3,NaN,USA
5041,Shanghai Calling,Daniel Hsia,Comedy|Drama|Romance,100.0,2012.0,NaN,PG-13,6.3,10443.0,Alan Ruck,Daniel Henney,Eliza Coupe,5.0,2386,6.3,NaN,USA
5042,My Date with Drew,Jon Gunn,Documentary,90.0,2004.0,1100.0,PG,6.6,85222.0,John August,Brian Herzlinger,Jon Gunn,0.0,163,6.6,actress name in title|crush|date|four word tit...,USA

In [6]:
cleaned_movie_df.genres = cleaned_movie_df.genres.str.split('|')

C:\Users\kaoti\anaconda3\lib\site-packages\pandas\core\generic.py:5168: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [7]:
cleaned_movie_df.plot_keywords = cleaned_movie_df.plot_keywords.str.split('|')

In [8]:
cleaned_movie_df['profit'] = cleaned_movie_df['gross']- cleaned_movie_df['budget']

<ipython-input-8-19c34b7262b0>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_movie_df['profit'] = cleaned_movie_df['gross']- cleaned_movie_df['budget']

In [9]:
comparison_column = np.where(cleaned_movie_df["budget"] <= cleaned_movie_df["gross"], True, False)

In [10]:
cleaned_movie_df['breakeven'] = comparison_column

<ipython-input-10-5b19a571f6c2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_movie_df['breakeven'] = comparison_column

In [11]:
cleaned_movie_df = cleaned_movie_df.drop_duplicates(subset=['title'])

In [12]:
cleaned_movie_df['gross(in millions USD)'] = cleaned_movie_df['gross']/1000000

<ipython-input-12-a676bd7a0432>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_movie_df['gross(in millions USD)'] = cleaned_movie_df['gross']/1000000

In [13]:
cleaned_movie_df['budget(in millions USD)'] = cleaned_movie_df['budget']/1000000

<ipython-input-13-d5469ac96c32>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_movie_df['budget(in millions USD)'] = cleaned_movie_df['budget']/1000000

In [14]:
cleaned_movie_df['profit(in millions USD)'] = cleaned_movie_df['profit']/1000000

<ipython-input-14-b25518f2b02a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_movie_df['profit(in millions USD)'] = cleaned_movie_df['profit']/1000000

In [25]:
cleaned_movie_df = cleaned_movie_df.drop(columns= ['gross','budget','profit'])

In [26]:
cleaned_movie_df

,title,director_name,genres,duration,title_year,content_rating,imdb_score,actor_1_name,actor_2_name,actor_3_name,facenumber_in_poster,cast_total_facebook_likes,imdb_score,plot_keywords,country,breakeven,gross(in millions USD),budget(in millions USD),profit(in millions USD)
0,Avatar,James Cameron,"[Action, Adventure, Fantasy, Sci-Fi]",178.0,2009.0,PG-13,7.9,CCH Pounder,Joel David Moore,Wes Studi,0.0,4834,7.9,"[avatar, future, marine, native, paraplegic]",USA,True,760.505847,237.0000,523.505847
1,Pirates of the Caribbean: At World's End,Gore Verbinski,"[Action, Adventure, Fantasy]",169.0,2007.0,PG-13,7.1,Johnny Depp,Orlando Bloom,Jack Davenport,0.0,48350,7.1,"[goddess, marriage ceremony, marriage proposal...",USA,True,309.404152,300.0000,9.404152
2,Spectre,Sam Mendes,"[Action, Adventure, Thriller]",148.0,2015.0,PG-13,6.8,Christoph Waltz,Rory Kinnear,Stephanie Sigman,1.0,11700,6.8,"[bomb, espionage, sequel, spy, terrorist]",UK,False,200.074175,245.0000,-44.925825
3,The Dark Knight Rises,Christopher Nolan,"[Action, Thriller]",164.0,2012.0,PG-13,8.5,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,0.0,106759,8.5,"[deception, imprisonment, lawlessness, police ...",USA,True,448.130642,250.0000,198.130642
4,Star Wars: Episode VII - The Force Awakens ...,Doug Walker,[Documentary],NaN,NaN,NaN,7.1,Doug Walker,Rob Walker,NaN,0.0,143,7.1,NaN,NaN,False,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Signed Sealed Delivered,Scott Smith,"[Comedy, Drama]",87.0,2013.0,NaN,7.7,Eric Mabius,Daphne Zuniga,Crystal Lowe,2.0,2283,7.7,"[fraud, postal worker, prison, theft, trial]",Canada,False,NaN,NaN,NaN
5039,The Following,NaN,"[Crime, Drama, Mystery, Thriller]",43.0,NaN,TV-14,7.5,Natalie Zea,Valorie Curry,Sam Underwood,1.0,1753,7.5,"[cult, fbi, hideout, prison escape, serial kil...",USA,False,NaN,NaN,NaN
5040,A Plague So Pleasant,Benjamin Roberds,"[Drama, Horror, Thriller]",76.0,2013.0,NaN,6.3,Eva Boehnke,Maxwell Moody,David Chandler,0.0,0,6.3,NaN,USA,False,NaN,0.0014,NaN
5041,Shanghai Calling,Daniel Hsia,"[Comedy, Drama, Romance]",100.0,2012.0,PG-13,6.3,Alan Ruck,Daniel Henney,Eliza Coupe,5.0,2386,6.3,NaN,USA,False,0.010443,NaN,NaN
5042,My Date with Drew,Jon Gunn,[Documentary],90.0,2004.0,PG,6.6,John August,Brian Herzlinger,Jon Gunn,0.0,163,6.6,"[actress name in title, crush, date, four word...",USA,True,0.085222,0.0011,0.084122

In [27]:
cleaned_movie_df['title'].astype("string")

0                                                  Avatar
1                Pirates of the Caribbean: At World's End
2                                                 Spectre
3                                   The Dark Knight Rises
4       Star Wars: Episode VII - The Force Awakens    ...
                              ...
5038                              Signed Sealed Delivered
5039                            The Following
5040                                 A Plague So Pleasant
5041                                     Shanghai Calling
5042                                    My Date with Drew
Name: title, Length: 4917, dtype: string

In [28]:
script_df['title'].astype("string")

0       10 Things I Hate About You
1                               12
2                   12 and Holding
3                       12 Monkeys
4                 12 Years a Slave
                   ...
1206               You've Got Mail
1207               Youth in Revolt
1208              Zero Dark Thirty
1209                    Zerophilia
1210                      Zootopia
Name: title, Length: 1211, dtype: string

In [29]:
script_df.dtypes

title          object
Swear_Count     int64
Fuck_Count      int64
Shit_Count      int64
Bitch_Count     int64
Cunt_Count      int64
Profanity      object
dtype: object

In [30]:
movie_swear_df = pd.merge(cleaned_movie_df,script_df,how='inner',on='title')
#movie_df.join(script_df, on='title',how='outer')

movie_swear_df

,title,director_name,genres,duration,title_year,content_rating,imdb_score,actor_1_name,actor_2_name,actor_3_name,...,breakeven,gross(in millions USD),budget(in millions USD),profit(in millions USD),Swear_Count,Fuck_Count,Shit_Count,Bitch_Count,Cunt_Count,Profanity
0,Avatar,James Cameron,"[Action, Adventure, Fantasy, Sci-Fi]",178.0,2009.0,PG-13,7.9,CCH Pounder,Joel David Moore,Wes Studi,...,True,760.505847,237.000,523.505847,18,1,11,6,0,TRUE
1,The Dark Knight Rises,Christopher Nolan,"[Action, Thriller]",164.0,2012.0,PG-13,8.5,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,...,True,448.130642,250.000,198.130642,2,0,0,2,0,TRUE
2,Harry Potter and the Half-Blood Prince,David Yates,"[Adventure, Family, Fantasy, Mystery]",153.0,2009.0,PG,7.5,Alan Rickman,Daniel Radcliffe,Rupert Grint,...,True,301.956980,250.000,51.956980,0,0,0,0,0,[]
3,Pirates of the Caribbean: Dead Man's Chest,Gore Verbinski,"[Action, Adventure, Fantasy]",151.0,2006.0,PG-13,7.3,Johnny Depp,Orlando Bloom,Jack Davenport,...,True,423.032628,225.000,198.032628,0,0,0,0,0,[]
4,The Avengers,Joss Whedon,"[Action, Adventure, Sci-Fi]",173.0,2012.0,PG-13,8.1,Chris Hemsworth,Robert Downey Jr.,Scarlett Johansson,...,True,623.279547,220.000,403.279547,24,13,10,1,0,TRUE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
741,Cube,Vincenzo Natali,"[Mystery, Sci-Fi, Thriller]",90.0,1997.0,R,7.3,David Hewlett,Julian Richings,Nicole de Boer,...,True,0.489220,0.365,0.124220,26,24,1,1,0,TRUE
742,Swingers,Doug Liman,"[Comedy, Drama]",96.0,1996.0,R,7.4,Jon Favreau,Alex DÃ©sert,Blake Lindsley,...,True,4.505922,0.200,4.305922,52,12,20,20,0,TRUE
743,Pi,Darren Aronofsky,"[Drama, Mystery, Thriller]",84.0,1998.0,R,7.5,Mark Margolis,Clint Mansell,Stanley B. Herman,...,True,3.216970,0.060,3.156970,13,10,3,0,0,TRUE
744,Clerks,Kevin Smith,[Comedy],102.0,1994.0,R,7.8,Jason Mewes,Brian O'Halloran,Jeff Anderson,...,True,3.151130,0.230,2.921130,118,78,35,2,3,TRUE
745,El Mariachi,Robert Rodriguez,"[Action, Crime, Drama, Romance, Thriller]",81.0,1992.0,R,6.9,Carlos Gallardo,Peter Marquardt,Consuelo GÃ³mez,...,True,2.040920,0.007,2.033920,0,0,0,0,0,[]

In [31]:
movie_swear_df.to_csv("Resources/movie_swear.csv")

In [32]:
movie_swear_df.head()

,title,director_name,genres,duration,title_year,content_rating,imdb_score,actor_1_name,actor_2_name,actor_3_name,...,breakeven,gross(in millions USD),budget(in millions USD),profit(in millions USD),Swear_Count,Fuck_Count,Shit_Count,Bitch_Count,Cunt_Count,Profanity
0,Avatar,James Cameron,"[Action, Adventure, Fantasy, Sci-Fi]",178.0,2009.0,PG-13,7.9,CCH Pounder,Joel David Moore,Wes Studi,...,True,760.505847,237.0,523.505847,18,1,11,6,0,TRUE
1,The Dark Knight Rises,Christopher Nolan,"[Action, Thriller]",164.0,2012.0,PG-13,8.5,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,...,True,448.130642,250.0,198.130642,2,0,0,2,0,TRUE
2,Harry Potter and the Half-Blood Prince,David Yates,"[Adventure, Family, Fantasy, Mystery]",153.0,2009.0,PG,7.5,Alan Rickman,Daniel Radcliffe,Rupert Grint,...,True,301.956980,250.0,51.956980,0,0,0,0,0,[]
3,Pirates of the Caribbean: Dead Man's Chest,Gore Verbinski,"[Action, Adventure, Fantasy]",151.0,2006.0,PG-13,7.3,Johnny Depp,Orlando Bloom,Jack Davenport,...,True,423.032628,225.0,198.032628,0,0,0,0,0,[]
4,The Avengers,Joss Whedon,"[Action, Adventure, Sci-Fi]",173.0,2012.0,PG-13,8.1,Chris Hemsworth,Robert Downey Jr.,Scarlett Johansson,...,True,623.279547,220.0,403.279547,24,13,10,1,0,TRUE

In [ ]:
# Create database connection and load quake.df into database
rds_connection_string = "postgres:postgres@localhost:5432/movie_swear_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [ ]:
cleaned_movie_df.to_sql(name='movie',con=engine, if_exists='replace',index=False)

In [ ]:
script_df.to_sql(name='script',con=engine, if_exists='replace',index=False)

In [ ]:
movie_swear_df.to_sql(name='movie_swear',con=engine, if_exists='replace',index=False)