In [1]:
# Dependencies and Setup
import pandas as pd
import json

# SQL Alchemy Dependencies
import sqlalchemy
from sqlalchemy import create_engine

In [2]:
# Read movie_metadata.csv into movie_df
movie_df = pd.read_csv("Resources/movie_metadata.csv")
movie_df.rename(columns={'movie_title':'title'}, inplace=True)

In [3]:
# Read all_script.csv into script_df
script_df = pd.read_csv("Resources/all_script.csv")
script_df

,title,Swear_Count,Fuck_Count,Shit_Count,Bitch_Count,Profanity
0,10 Things I Hate About You,15,3,6,6,1
1,12,2,2,0,0,1
2,12 and Holding,21,10,10,1,1
3,12 Monkeys,17,11,4,2,1
4,12 Years a Slave,1,0,0,1,1
...,...,...,...,...,...,...
1206,You've Got Mail,9,4,4,1,1
1207,Youth in Revolt,6,2,4,0,1
1208,Zero Dark Thirty,43,40,2,1,1
1209,Zerophilia,18,14,4,0,1
1210,Zootopia,0,0,0,0,0

In [4]:
movie_df.dtypes

color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
title                         object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object

In [10]:
# Select
cleaned_movie_df = movie_df[["title","director_name","genres","duration","title_year","budget","content_rating","imdb_score","gross","actor_1_name","actor_2_name","facenumber_in_poster","country"]]
cleaned_movie_df

,title,director_name,genres,duration,title_year,budget,content_rating,imdb_score,gross,actor_1_name,actor_2_name,facenumber_in_poster,country
0,Avatar,James Cameron,Action|Adventure|Fantasy|Sci-Fi,178.0,2009.0,237000000.0,PG-13,7.9,760505847.0,CCH Pounder,Joel David Moore,0.0,USA
1,Pirates of the Caribbean: At World's End,Gore Verbinski,Action|Adventure|Fantasy,169.0,2007.0,300000000.0,PG-13,7.1,309404152.0,Johnny Depp,Orlando Bloom,0.0,USA
2,Spectre,Sam Mendes,Action|Adventure|Thriller,148.0,2015.0,245000000.0,PG-13,6.8,200074175.0,Christoph Waltz,Rory Kinnear,1.0,UK
3,The Dark Knight Rises,Christopher Nolan,Action|Thriller,164.0,2012.0,250000000.0,PG-13,8.5,448130642.0,Tom Hardy,Christian Bale,0.0,USA
4,Star Wars: Episode VII - The Force Awakens ...,Doug Walker,Documentary,NaN,NaN,NaN,NaN,7.1,NaN,Doug Walker,Rob Walker,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Signed Sealed Delivered,Scott Smith,Comedy|Drama,87.0,2013.0,NaN,NaN,7.7,NaN,Eric Mabius,Daphne Zuniga,2.0,Canada
5039,The Following,NaN,Crime|Drama|Mystery|Thriller,43.0,NaN,NaN,TV-14,7.5,NaN,Natalie Zea,Valorie Curry,1.0,USA
5040,A Plague So Pleasant,Benjamin Roberds,Drama|Horror|Thriller,76.0,2013.0,1400.0,NaN,6.3,NaN,Eva Boehnke,Maxwell Moody,0.0,USA
5041,Shanghai Calling,Daniel Hsia,Comedy|Drama|Romance,100.0,2012.0,NaN,PG-13,6.3,10443.0,Alan Ruck,Daniel Henney,5.0,USA
5042,My Date with Drew,Jon Gunn,Documentary,90.0,2004.0,1100.0,PG,6.6,85222.0,John August,Brian Herzlinger,0.0,USA

In [12]:
cleaned_movie_df.genres = cleaned_movie_df.genres.str.split('|')

C:\Users\tiffa\Anaconda3\lib\site-packages\pandas\core\generic.py:5168: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [13]:
cleaned_movie_df['title'].astype("string")

0                                                  Avatar
1                Pirates of the Caribbean: At World's End
2                                                 Spectre
3                                   The Dark Knight Rises
4       Star Wars: Episode VII - The Force Awakens    ...
                              ...
5038                              Signed Sealed Delivered
5039                            The Following
5040                                 A Plague So Pleasant
5041                                     Shanghai Calling
5042                                    My Date with Drew
Name: title, Length: 5043, dtype: string

In [14]:
script_df['title'].astype("string")

0       10 Things I Hate About You
1                               12
2                   12 and Holding
3                       12 Monkeys
4                 12 Years a Slave
                   ...
1206               You've Got Mail
1207               Youth in Revolt
1208              Zero Dark Thirty
1209                    Zerophilia
1210                      Zootopia
Name: title, Length: 1211, dtype: string

In [9]:
script_df.dtypes

title          object
Swear_Count     int64
Fuck_Count      int64
Shit_Count      int64
Bitch_Count     int64
Profanity       int64
dtype: object

In [11]:
movie_swear_df = pd.merge(cleaned_movie_df,script_df,how='inner',on='title')
#movie_df.join(script_df, on='title',how='outer')

movie_swear_df

,title,director_name,genres,duration,title_year,budget,content_rating,imdb_score,gross,actor_1_name,actor_2_name,facenumber_in_poster,Swear_Count,Fuck_Count,Shit_Count,Bitch_Count,Profanity
0,Avatar,James Cameron,Action|Adventure|Fantasy|Sci-Fi,178.0,2009.0,237000000.0,PG-13,7.9,760505847.0,CCH Pounder,Joel David Moore,0.0,8,1,5,2,1
1,Harry Potter and the Half-Blood Prince,David Yates,Adventure|Family|Fantasy|Mystery,153.0,2009.0,250000000.0,PG,7.5,301956980.0,Alan Rickman,Daniel Radcliffe,3.0,0,0,0,0,0
2,Pirates of the Caribbean: Dead Man's Chest,Gore Verbinski,Action|Adventure|Fantasy,151.0,2006.0,225000000.0,PG-13,7.3,423032628.0,Johnny Depp,Orlando Bloom,2.0,0,0,0,0,0
3,Men in Black 3,Barry Sonnenfeld,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,106.0,2012.0,225000000.0,PG-13,6.8,179020854.0,Will Smith,Michael Stuhlbarg,1.0,1,0,1,0,1
4,King Kong,Peter Jackson,Action|Adventure|Drama|Romance,201.0,2005.0,207000000.0,PG-13,7.2,218051260.0,Naomi Watts,Thomas Kretschmann,0.0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,Cube,Vincenzo Natali,Mystery|Sci-Fi|Thriller,90.0,1997.0,365000.0,R,7.3,489220.0,David Hewlett,Julian Richings,0.0,23,23,0,0,1
616,Swingers,Doug Liman,Comedy|Drama,96.0,1996.0,200000.0,R,7.4,4505922.0,Jon Favreau,Alex DÃ©sert,0.0,22,11,8,3,1
617,Pi,Darren Aronofsky,Drama|Mystery|Thriller,84.0,1998.0,60000.0,R,7.5,3216970.0,Mark Margolis,Clint Mansell,0.0,11,10,1,0,1
618,Clerks,Kevin Smith,Comedy,102.0,1994.0,230000.0,R,7.8,3151130.0,Jason Mewes,Brian O'Halloran,4.0,85,69,16,0,1
619,El Mariachi,Robert Rodriguez,Action|Crime|Drama|Romance|Thriller,81.0,1992.0,7000.0,R,6.9,2040920.0,Carlos Gallardo,Peter Marquardt,0.0,0,0,0,0,0

In [13]:
movie_swear_df.to_csv("Resources/movie_swear.csv")

In [15]:
# Create database connection and load quake.df into database
rds_connection_string = "postgres:postgres@localhost:5432/movie_swear_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [52]:
cleaned_movie_df.to_sql(name='movie',con=engine, if_exists='replace',index=False)

In [53]:
script_df.to_sql(name='script',con=engine, if_exists='replace',index=False)

In [16]:
movie_swear_df.to_sql(name='movie_swear',con=engine, if_exists='replace',index=False)