In [11]:
# Dependencies and Setup
import pandas as pd
import json
import numpy as np

# SQL Alchemy Dependencies
import sqlalchemy
from sqlalchemy import create_engine

In [2]:
# Read movie_metadata.csv into movie_df
movie_df = pd.read_csv("Resources/movie_metadata.csv")
movie_df.rename(columns={'movie_title':'title'}, inplace=True)

In [3]:
# Read all_script.csv into script_df
script_df = pd.read_csv("Resources/updated_all_script.csv")
script_df

,title,Swear_Count,Fuck_Count,Shit_Count,Bitch_Count,Cunt_Count,Profanity
0,10 Things I Hate About You,15,3,6,6,0,TRUE
1,12,2,2,0,0,0,TRUE
2,12 and Holding,21,10,10,1,0,TRUE
3,12 Monkeys,17,11,4,2,0,TRUE
4,12 Years a Slave,1,0,0,1,0,TRUE
...,...,...,...,...,...,...,...
1206,You've Got Mail,9,4,4,1,0,TRUE
1207,Youth in Revolt,6,2,4,0,0,TRUE
1208,Zero Dark Thirty,44,41,2,1,0,TRUE
1209,Zerophilia,18,14,4,0,0,TRUE
1210,Zootopia,0,0,0,0,0,[]

In [4]:
movie_df.dtypes

color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
title                         object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object

In [5]:
# Select
cleaned_movie_df = movie_df[["title","director_name","genres","duration","title_year","budget","content_rating","imdb_score","gross","actor_1_name","actor_2_name","actor_3_name","facenumber_in_poster","cast_total_facebook_likes","imdb_score","plot_keywords","country"]]
cleaned_movie_df

,title,director_name,genres,duration,title_year,budget,content_rating,imdb_score,gross,actor_1_name,actor_2_name,actor_3_name,facenumber_in_poster,cast_total_facebook_likes,imdb_score,plot_keywords,country
0,Avatar,James Cameron,Action|Adventure|Fantasy|Sci-Fi,178.0,2009.0,237000000.0,PG-13,7.9,760505847.0,CCH Pounder,Joel David Moore,Wes Studi,0.0,4834,7.9,avatar|future|marine|native|paraplegic,USA
1,Pirates of the Caribbean: At World's End,Gore Verbinski,Action|Adventure|Fantasy,169.0,2007.0,300000000.0,PG-13,7.1,309404152.0,Johnny Depp,Orlando Bloom,Jack Davenport,0.0,48350,7.1,goddess|marriage ceremony|marriage proposal|pi...,USA
2,Spectre,Sam Mendes,Action|Adventure|Thriller,148.0,2015.0,245000000.0,PG-13,6.8,200074175.0,Christoph Waltz,Rory Kinnear,Stephanie Sigman,1.0,11700,6.8,bomb|espionage|sequel|spy|terrorist,UK
3,The Dark Knight Rises,Christopher Nolan,Action|Thriller,164.0,2012.0,250000000.0,PG-13,8.5,448130642.0,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,0.0,106759,8.5,deception|imprisonment|lawlessness|police offi...,USA
4,Star Wars: Episode VII - The Force Awakens ...,Doug Walker,Documentary,NaN,NaN,NaN,NaN,7.1,NaN,Doug Walker,Rob Walker,NaN,0.0,143,7.1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Signed Sealed Delivered,Scott Smith,Comedy|Drama,87.0,2013.0,NaN,NaN,7.7,NaN,Eric Mabius,Daphne Zuniga,Crystal Lowe,2.0,2283,7.7,fraud|postal worker|prison|theft|trial,Canada
5039,The Following,NaN,Crime|Drama|Mystery|Thriller,43.0,NaN,NaN,TV-14,7.5,NaN,Natalie Zea,Valorie Curry,Sam Underwood,1.0,1753,7.5,cult|fbi|hideout|prison escape|serial killer,USA
5040,A Plague So Pleasant,Benjamin Roberds,Drama|Horror|Thriller,76.0,2013.0,1400.0,NaN,6.3,NaN,Eva Boehnke,Maxwell Moody,David Chandler,0.0,0,6.3,NaN,USA
5041,Shanghai Calling,Daniel Hsia,Comedy|Drama|Romance,100.0,2012.0,NaN,PG-13,6.3,10443.0,Alan Ruck,Daniel Henney,Eliza Coupe,5.0,2386,6.3,NaN,USA
5042,My Date with Drew,Jon Gunn,Documentary,90.0,2004.0,1100.0,PG,6.6,85222.0,John August,Brian Herzlinger,Jon Gunn,0.0,163,6.6,actress name in title|crush|date|four word tit...,USA

In [6]:
cleaned_movie_df.genres = cleaned_movie_df.genres.str.split('|')

C:\Users\kaoti\anaconda3\lib\site-packages\pandas\core\generic.py:5168: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [7]:
cleaned_movie_df.plot_keywords = cleaned_movie_df.plot_keywords.str.split('|')

In [9]:
cleaned_movie_df['profit'] = cleaned_movie_df['gross']- cleaned_movie_df['budget']

<ipython-input-9-19c34b7262b0>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_movie_df['profit'] = cleaned_movie_df['gross']- cleaned_movie_df['budget']

In [18]:
comparison_column = np.where(cleaned_movie_df["budget"] <= cleaned_movie_df["gross"], True, False)

In [19]:
cleaned_movie_df['breakeven'] = comparison_column

<ipython-input-19-5b19a571f6c2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_movie_df['breakeven'] = comparison_column

In [40]:
cleaned_movie_df = cleaned_movie_df.drop_duplicates(subset=['title'])

In [41]:
cleaned_movie_df

,title,director_name,genres,duration,title_year,budget,content_rating,imdb_score,gross,actor_1_name,actor_2_name,actor_3_name,facenumber_in_poster,cast_total_facebook_likes,imdb_score,plot_keywords,country,profit,breakeven
0,Avatar,James Cameron,"[Action, Adventure, Fantasy, Sci-Fi]",178.0,2009.0,237000000.0,PG-13,7.9,760505847.0,CCH Pounder,Joel David Moore,Wes Studi,0.0,4834,7.9,"[avatar, future, marine, native, paraplegic]",USA,523505847.0,True
1,Pirates of the Caribbean: At World's End,Gore Verbinski,"[Action, Adventure, Fantasy]",169.0,2007.0,300000000.0,PG-13,7.1,309404152.0,Johnny Depp,Orlando Bloom,Jack Davenport,0.0,48350,7.1,"[goddess, marriage ceremony, marriage proposal...",USA,9404152.0,True
2,Spectre,Sam Mendes,"[Action, Adventure, Thriller]",148.0,2015.0,245000000.0,PG-13,6.8,200074175.0,Christoph Waltz,Rory Kinnear,Stephanie Sigman,1.0,11700,6.8,"[bomb, espionage, sequel, spy, terrorist]",UK,-44925825.0,False
3,The Dark Knight Rises,Christopher Nolan,"[Action, Thriller]",164.0,2012.0,250000000.0,PG-13,8.5,448130642.0,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,0.0,106759,8.5,"[deception, imprisonment, lawlessness, police ...",USA,198130642.0,True
4,Star Wars: Episode VII - The Force Awakens ...,Doug Walker,[Documentary],NaN,NaN,NaN,NaN,7.1,NaN,Doug Walker,Rob Walker,NaN,0.0,143,7.1,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Signed Sealed Delivered,Scott Smith,"[Comedy, Drama]",87.0,2013.0,NaN,NaN,7.7,NaN,Eric Mabius,Daphne Zuniga,Crystal Lowe,2.0,2283,7.7,"[fraud, postal worker, prison, theft, trial]",Canada,NaN,False
5039,The Following,NaN,"[Crime, Drama, Mystery, Thriller]",43.0,NaN,NaN,TV-14,7.5,NaN,Natalie Zea,Valorie Curry,Sam Underwood,1.0,1753,7.5,"[cult, fbi, hideout, prison escape, serial kil...",USA,NaN,False
5040,A Plague So Pleasant,Benjamin Roberds,"[Drama, Horror, Thriller]",76.0,2013.0,1400.0,NaN,6.3,NaN,Eva Boehnke,Maxwell Moody,David Chandler,0.0,0,6.3,NaN,USA,NaN,False
5041,Shanghai Calling,Daniel Hsia,"[Comedy, Drama, Romance]",100.0,2012.0,NaN,PG-13,6.3,10443.0,Alan Ruck,Daniel Henney,Eliza Coupe,5.0,2386,6.3,NaN,USA,NaN,False
5042,My Date with Drew,Jon Gunn,[Documentary],90.0,2004.0,1100.0,PG,6.6,85222.0,John August,Brian Herzlinger,Jon Gunn,0.0,163,6.6,"[actress name in title, crush, date, four word...",USA,84122.0,True

In [42]:
cleaned_movie_df['title'].astype("string")

0                                                  Avatar
1                Pirates of the Caribbean: At World's End
2                                                 Spectre
3                                   The Dark Knight Rises
4       Star Wars: Episode VII - The Force Awakens    ...
                              ...
5038                              Signed Sealed Delivered
5039                            The Following
5040                                 A Plague So Pleasant
5041                                     Shanghai Calling
5042                                    My Date with Drew
Name: title, Length: 4917, dtype: string

In [43]:
script_df['title'].astype("string")

0       10 Things I Hate About You
1                               12
2                   12 and Holding
3                       12 Monkeys
4                 12 Years a Slave
                   ...
1206               You've Got Mail
1207               Youth in Revolt
1208              Zero Dark Thirty
1209                    Zerophilia
1210                      Zootopia
Name: title, Length: 1211, dtype: string

In [44]:
script_df.dtypes

title          object
Swear_Count     int64
Fuck_Count      int64
Shit_Count      int64
Bitch_Count     int64
Cunt_Count      int64
Profanity      object
dtype: object

In [45]:
movie_swear_df = pd.merge(cleaned_movie_df,script_df,how='inner',on='title')
#movie_df.join(script_df, on='title',how='outer')

movie_swear_df

,title,director_name,genres,duration,title_year,budget,content_rating,imdb_score,gross,actor_1_name,...,plot_keywords,country,profit,breakeven,Swear_Count,Fuck_Count,Shit_Count,Bitch_Count,Cunt_Count,Profanity
0,Avatar,James Cameron,"[Action, Adventure, Fantasy, Sci-Fi]",178.0,2009.0,237000000.0,PG-13,7.9,760505847.0,CCH Pounder,...,"[avatar, future, marine, native, paraplegic]",USA,523505847.0,True,18,1,11,6,0,TRUE
1,The Dark Knight Rises,Christopher Nolan,"[Action, Thriller]",164.0,2012.0,250000000.0,PG-13,8.5,448130642.0,Tom Hardy,...,"[deception, imprisonment, lawlessness, police ...",USA,198130642.0,True,2,0,0,2,0,TRUE
2,Harry Potter and the Half-Blood Prince,David Yates,"[Adventure, Family, Fantasy, Mystery]",153.0,2009.0,250000000.0,PG,7.5,301956980.0,Alan Rickman,...,"[blood, book, love, potion, professor]",UK,51956980.0,True,0,0,0,0,0,[]
3,Pirates of the Caribbean: Dead Man's Chest,Gore Verbinski,"[Action, Adventure, Fantasy]",151.0,2006.0,225000000.0,PG-13,7.3,423032628.0,Johnny Depp,...,"[box office hit, giant squid, heart, liar's di...",USA,198032628.0,True,0,0,0,0,0,[]
4,The Avengers,Joss Whedon,"[Action, Adventure, Sci-Fi]",173.0,2012.0,220000000.0,PG-13,8.1,623279547.0,Chris Hemsworth,...,"[alien invasion, assassin, battle, iron man, s...",USA,403279547.0,True,24,13,10,1,0,TRUE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
741,Cube,Vincenzo Natali,"[Mystery, Sci-Fi, Thriller]",90.0,1997.0,365000.0,R,7.3,489220.0,David Hewlett,...,"[escape, labyrinth, maze, red light, trap]",Canada,124220.0,True,26,24,1,1,0,TRUE
742,Swingers,Doug Liman,"[Comedy, Drama]",96.0,1996.0,200000.0,R,7.4,4505922.0,Jon Favreau,...,"[actor, black panties, cult film, friend, upsk...",USA,4305922.0,True,52,12,20,20,0,TRUE
743,Pi,Darren Aronofsky,"[Drama, Mystery, Thriller]",84.0,1998.0,60000.0,R,7.5,3216970.0,Mark Margolis,...,"[mathematician, nature, numbers, pattern, usin...",USA,3156970.0,True,13,10,3,0,0,TRUE
744,Clerks,Kevin Smith,[Comedy],102.0,1994.0,230000.0,R,7.8,3151130.0,Jason Mewes,...,"[clerk, friend, hockey, video, video store]",USA,2921130.0,True,118,78,35,2,3,TRUE
745,El Mariachi,Robert Rodriguez,"[Action, Crime, Drama, Romance, Thriller]",81.0,1992.0,7000.0,R,6.9,2040920.0,Carlos Gallardo,...,"[assassin, death, guitar, gun, mariachi]",USA,2033920.0,True,0,0,0,0,0,[]

In [46]:
movie_swear_df.to_csv("Resources/movie_swear.csv")

In [47]:
movie_swear_df.head()

,title,director_name,genres,duration,title_year,budget,content_rating,imdb_score,gross,actor_1_name,...,plot_keywords,country,profit,breakeven,Swear_Count,Fuck_Count,Shit_Count,Bitch_Count,Cunt_Count,Profanity
0,Avatar,James Cameron,"[Action, Adventure, Fantasy, Sci-Fi]",178.0,2009.0,237000000.0,PG-13,7.9,760505847.0,CCH Pounder,...,"[avatar, future, marine, native, paraplegic]",USA,523505847.0,True,18,1,11,6,0,TRUE
1,The Dark Knight Rises,Christopher Nolan,"[Action, Thriller]",164.0,2012.0,250000000.0,PG-13,8.5,448130642.0,Tom Hardy,...,"[deception, imprisonment, lawlessness, police ...",USA,198130642.0,True,2,0,0,2,0,TRUE
2,Harry Potter and the Half-Blood Prince,David Yates,"[Adventure, Family, Fantasy, Mystery]",153.0,2009.0,250000000.0,PG,7.5,301956980.0,Alan Rickman,...,"[blood, book, love, potion, professor]",UK,51956980.0,True,0,0,0,0,0,[]
3,Pirates of the Caribbean: Dead Man's Chest,Gore Verbinski,"[Action, Adventure, Fantasy]",151.0,2006.0,225000000.0,PG-13,7.3,423032628.0,Johnny Depp,...,"[box office hit, giant squid, heart, liar's di...",USA,198032628.0,True,0,0,0,0,0,[]
4,The Avengers,Joss Whedon,"[Action, Adventure, Sci-Fi]",173.0,2012.0,220000000.0,PG-13,8.1,623279547.0,Chris Hemsworth,...,"[alien invasion, assassin, battle, iron man, s...",USA,403279547.0,True,24,13,10,1,0,TRUE

In [27]:
# Create database connection and load quake.df into database
rds_connection_string = "postgres:postgres@localhost:5432/movie_swear_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [28]:
cleaned_movie_df.to_sql(name='movie',con=engine, if_exists='replace',index=False)

OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "postgres"

(Background on this error at: http://sqlalche.me/e/13/e3q8)

In [53]:
script_df.to_sql(name='script',con=engine, if_exists='replace',index=False)

In [16]:
movie_swear_df.to_sql(name='movie_swear',con=engine, if_exists='replace',index=False)